import type { Metadata } from "next";
import {Inter as FontSans} from "next/font/google";
import {cn} from "@/lib/utils";
import "./globals.css";


const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("min-h-screen bg-gradient-to-br from-gray-100 to-blue-50 font-sans antialiased", fontSans.variable)}>
        {children}
      </body>
    </html>
  );
}

// Ejemplo usando fetch
fetch('http://localhost:4000/api/register', {
  method: 'POST',
  headers: {
    'Content-Type': 'application/json'
  },
  body: JSON.stringify({ campo1: 'valor1', campo2: 'valor2' })
})
